const PizzaData = [
    {
        id: 1,
        name: "Margherita",
        description: "Tomato, Mozzarella, Basil",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian", "Hot & Spicy","Vegi Sizzler","Tuna Supreme",
                "Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ","Peri Peri Lover",
                "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
                "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/Margherita.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 2,
        name: "Pepperoni",
        description: "Mozzarella, Pepperoni",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Vegi Supreme", "American Hot", "Hawaiian", "Hot & Spicy","Vegi Sizzler","Tuna Supreme",
            "Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ","Peri Peri Lover",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/Pepperoni.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 3,
        name: "Vegi Supreme",
        description: "Tomatoes, Onions, Green & Red Peppers, Sweetcorn, Mushrooms",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "American Hot", "Hawaiian", "Hot & Spicy","Vegi Sizzler","Tuna Supreme",
            "Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ","Peri Peri Lover",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/Vegi-Supreme.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 4,
        name: "American Hot",
        description: "Onions, Pepperoni, Green Jalapenos ",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "Hawaiian", "Hot & Spicy","Vegi Sizzler","Tuna Supreme",
            "Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ","Peri Peri Lover",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/American-Hot.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 5,
        name: "Hawaiian",
        description: "Ham, Pineapple, Mushrooms",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hot & Spicy","Vegi Sizzler","Tuna Supreme",
            "Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ","Peri Peri Lover",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/Hawaiian.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 6,
        name: "Hot & Spicy",
        description: "Ground Beef, Onions, Green & Red Peppers, Green Jalapenos",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Vegi Sizzler","Tuna Supreme",
            "Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ","Peri Peri Lover",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/hot-and-spicy.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 7,
        name: "Vegi Sizzler",
        description: "Green & Red Peppers, Onions, Tomatoes, Green Chilles",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Tuna Supreme",
            "Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ","Peri Peri Lover",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/vegi-sizzler.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 8,
        name: "Tuna Supreme",
        description: "Tuna, Sweetcorn, Onions",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ","Peri Peri Lover",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/tuna-supreme.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 9,
        name: "Texas BBQ",
        description: "BBQ Sauce, Smoky Bacon, Chicken Breast Strips, Onions, Green & Red Peppers",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Tuna Supreme","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ","Peri Peri Lover",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/texas-bbq.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 10,
        name: "Vegi Volcano",
        description: "Onions, Green & Red Peppers, Tomatoes, Green Jalapenos, Extra Mozzarella",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Tuna Supreme","Texas BBQ","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ","Peri Peri Lover",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/vegi-volcano.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 11,
        name: "Ham & Pineapple",
        description: "Ham, Pineapple",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Tuna Supreme","Texas BBQ","Vegi Volcano","Chicken Lover","Mexican Hot","Meaty BBQ","Peri Peri Lover",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/ham-and-pineapple.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 12,
        name: "Chicken Lover",
        description: "Chicken, Mozzarella, Cheddar",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Tuna Supreme","Texas BBQ","Vegi Volcano","Ham & Pineapple","Mexican Hot","Meaty BBQ","Peri Peri Lover",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/Chicken-lover.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 13,
        name: "Mexican Hot",
        description: "Beef, Red Onions, Green Peppers, Green Jalapenos",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Tuna Supreme","Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Meaty BBQ","Peri Peri Lover",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/mexican-hot.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 14,
        name: "Meaty BBQ",
        description: "BBQ Sauce, Mozzarella, Beef, Ham, Meatballs, Bacon, Chicken",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Tuna Supreme","Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Peri Peri Lover",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/meaty-bbq.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 15,
        name: "Peri Peri Lover",
        description: "Peri Peri Chicken, Chorizo, Roquito Peppers, Red Onions, Tomatoes",
        price: 10.99,
        vegan: false,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Tuna Supreme","Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ",
            "Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/peri-peri-lover.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 16,
        name: "Plant-based Margherita",
        description: "Tomatoes, Plant-based Cheese, Herbs",
        price: 10.99,
        vegan: true,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Tuna Supreme","Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ",
            "Peri Peri Lover","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/plant-based-margherita.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 17,
        name: "Plant-based American Hot",
        description: "Tomato Sauce, Plant-based Cheese, Plant-based Soya & Wheat Pepperoni, Red Onions, Green Jalapenos",
        price: 10.99,
        vegan: true,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Tuna Supreme","Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ",
            "Peri Peri Lover","Plant-based Margherita","Plant-based Pepperoni","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/plant-based-american-hot.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 18,
        name: "Plant-based Pepperoni",
        description: "Tomato Sauce, Plant-based Cheese, Plant-based Soya & Wheat Pepperoni",
        price: 10.99,
        vegan: true,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Tuna Supreme","Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ",
            "Peri Peri Lover","Plant-based Margherita","Plant-based American Hot","Plant-based Vegi Supreme","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/plant-based-pepperoni.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 19,
        name: "Plant-based Vegi Supreme",
        description: "Tomato Sauce, Plant-based Cheese, Red Onions, Red & Green Peppers, Tomatoes, Mushrooms, Sweetcorn",
        price: 10.99,
        vegan: true,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Tuna Supreme","Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ",
            "Peri Peri Lover","Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Chicken Winner",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
        image: '/images/plant-based-vegi-supreme.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 20,
        name: "Plant-based Chicken Winner",
        description: "Tomato Sauce, Plant-based Cheese, Plant-based Soya Strips, Red Onions, Red & Green Peppers",
        price: 10.99,
        vegan: true,
        glutenFree: false,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Tuna Supreme","Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ",
            "Peri Peri Lover","Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme",
            "Gluten Free Vegi Supreme","Gluten Free Texas BBQ"],
       image: '/images/plant-based-chicken-winner.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 21,
        name: "Gluten Free Vegi Supreme",
        description: "Tomato Sauce, Mozzarella, Red Onions, Red & Green Peppers, Tomatoes, Mushrooms, Sweetcorn",
        price: 10.99,
        vegan: false,
        glutenFree: true,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves: ["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
            "Tuna Supreme","Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ",
            "Peri Peri Lover","Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme",
            "Plant-based Chicken Winner","Gluten Free Texas BBQ"],
        image: '/images/gluten-free-vegi-supreme.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
    {
        id: 22,
        name: "Gluten Free Texas BBQ",
        description: "Mozzarella, BBQ Sauce, Red Onions, Red & Green Onions, Plain Chicken Strips, Smoked Bacon",
        price: 10.99,
        vegan: false,
        glutenFree: true,
        base: "Thin Italian",
        sizes: ["Small (8\")", "Medium (12\")", "Large (16\")", "Pizzanormous (20\")"],
        halves:["Margherita", "Pepperoni", "Vegi Supreme", "American Hot", "Hawaiian","Hot & Spicy","Vegi Sizzler",
        "Tuna Supreme","Texas BBQ","Vegi Volcano","Ham & Pineapple","Chicken Lover","Mexican Hot","Meaty BBQ",
        "Peri Peri Lover","Plant-based Margherita","Plant-based American Hot","Plant-based Pepperoni","Plant-based Vegi Supreme",
        "Plant-based Chicken Winner","Gluten Free Vegi Supreme"],
         image: '/images/gluten-free-texas-bbq.jpg',
        selectedSize: "Small (8\")", // Initial size
    },
];
export default PizzaData;
